---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Percy.
--- DateTime: 2024/12/25
---
local ant_path_matcher = require("src.ant_path_matcher")
print("#############")

matcher = ant_path_matcher:instance();
matcher:match("12", "2")

matcher:split("/test/**/aaa", "**")

local p = "/test/**/b/**aaa"
--local m_asterisk_contains = string.match(p, "**")
--local s_asterisk_contains = string.match(p, "*")
--local s_ask_contains = string.match(p, "?")

local res = matcher:contains(p, "*")

print("=============:" .. tostring(res))

local result = matcher:split(p, "**")
for k, v in ipairs(result) do
    print("key: " .. v)
end

res = matcher:ends(p, "aaa")
print("end: " .. tostring(res))






