---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Percy.
--- DateTime: 2024/12/30
---
local AntPathMatcher = require("src.AntPathMatcher")
ant_path_matcher = AntPathMatcher.new()

local pattern = "/bla/**/bla"
local url = "/bla/testing/testing/bla"
local compare = ant_path_matcher:match(pattern, url)
local expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/jd/a?c"
url = "/jd/abc"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/jd/a?c"
url = "/jd/ac"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/jd/a?c"
url = "/jd/axyzc"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/jd/a*c"
url = "/jd/ac"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "/jd/a*c"
url = "/jd/abc"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "/jd/a*c"
url = "/jd/axyzc"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "/jd/a*c"
url = "/jd/a"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "**"
url = ""
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "test"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/test"
url = "/test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "https://example.org"
url = "https://example.org"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "/test.jpg"
url = "test.jpg"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "t?st"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "??st"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "tes?"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "te??"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "te??"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "?es?"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "tes?"
url = "tes"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "tes?"
url = "testt"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "tes?"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*"
url = "testTest"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test/*"
url = "test/Test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test/*"
url = "test/t"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test/*"
url = "test/"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*test*"
url = "AnothertestTest"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*.*"
url = "test."
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*.*"
url = "test.test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "*.*"
url = "test.test.test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*aaa"
url = "testblaaaa"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*"
url = "tst"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "test*"
url = "tsttest"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*"
url = "test/"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*"
url = "test/t"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test/*"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*test*"
url = "tsttst"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*test"
url = "tsttst"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "*test"
url = "tsttst"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "test*aaa"
url = "test"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "test*aaa"
url = "testblaaab"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/?"
url = "/a"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/?/a"
url = "/a"
compare = ant_path_matcher:match(pattern, url)
expect = false
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/a/?"
url = "/a/b"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/??/a"
url = "/aa/a"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/a/??"
url = "/a/bb"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/?"
url = "/a"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/?"
url = "/a"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/**"
url = "/testing/testing"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/*/**"
url = "/testing/testing"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/**/*"
url = "/testing/testing"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))


pattern = "/bla/**/bla"
url = "/bla/testing/testing/bla"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/bla/**/bla"
url = "/bla/testing/testing/bla/bla"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/**/test"
url = "/bla/bla/test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/bla/**/**/bla"
url = "/bla/bla/bla/bla/bla/bla"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/bla*bla/test"
url = "/blaXXXbla/test"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))

pattern = "/*bla*/**/bla/**"
url = "/XXXblaXXXX/testing/testing/bla/testing/testing/"
compare = ant_path_matcher:match(pattern, url)
expect = true
print("pattern: " .. pattern ..", url: " .. url ..", compare: " .. tostring(compare) .. ", expect: " .. tostring(expect) .. " | approved: " .. tostring(expect == compare))
